name: Build Android

on: [push, pull_request]

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repository code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # 2) (Optional) Cache the Library folder to speed up subsequent builds
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android
          restore-keys: Library-

      # 3) Free disk space on the Ubuntu runner (helpful for large Android builds)
      - uses: jlumbroso/free-disk-space@v1.3.1

      # 4) Build the Unity project for Android
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          # Optionally specify your Unity version:
          # unityVersion: 2021.3.11f1

      # 5) Upload the Android build artifact (APK)
      - uses: actions/upload-artifact@v4
        with:
          name: Build-Android
          path: build/Android
